version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: '123456a'  # Mật khẩu cho tài khoản root
      MYSQL_USER: 'recommendation'    # Tài khoản người dùng bạn muốn tạo
      MYSQL_PASSWORD: '123456a'       # Mật khẩu cho tài khoản recommendation
      MYSQL_DATABASE: 'recommendation_db'  # Tên của cơ sở dữ liệu
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network:
